/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LargeMonstersRouteRouteImport } from './routes/largeMonsters.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LargeMonstersIndexRouteImport } from './routes/largeMonsters.index'
import { Route as LargeMonstersLargeMonsterGameIdRouteImport } from './routes/largeMonsters.$largeMonsterGameId'

const LargeMonstersRouteRoute = LargeMonstersRouteRouteImport.update({
  id: '/largeMonsters',
  path: '/largeMonsters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeMonstersIndexRoute = LargeMonstersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LargeMonstersRouteRoute,
} as any)
const LargeMonstersLargeMonsterGameIdRoute =
  LargeMonstersLargeMonsterGameIdRouteImport.update({
    id: '/$largeMonsterGameId',
    path: '/$largeMonsterGameId',
    getParentRoute: () => LargeMonstersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/largeMonsters': typeof LargeMonstersRouteRouteWithChildren
  '/largeMonsters/$largeMonsterGameId': typeof LargeMonstersLargeMonsterGameIdRoute
  '/largeMonsters/': typeof LargeMonstersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/largeMonsters/$largeMonsterGameId': typeof LargeMonstersLargeMonsterGameIdRoute
  '/largeMonsters': typeof LargeMonstersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/largeMonsters': typeof LargeMonstersRouteRouteWithChildren
  '/largeMonsters/$largeMonsterGameId': typeof LargeMonstersLargeMonsterGameIdRoute
  '/largeMonsters/': typeof LargeMonstersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/largeMonsters'
    | '/largeMonsters/$largeMonsterGameId'
    | '/largeMonsters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/largeMonsters/$largeMonsterGameId' | '/largeMonsters'
  id:
    | '__root__'
    | '/'
    | '/largeMonsters'
    | '/largeMonsters/$largeMonsterGameId'
    | '/largeMonsters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LargeMonstersRouteRoute: typeof LargeMonstersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/largeMonsters': {
      id: '/largeMonsters'
      path: '/largeMonsters'
      fullPath: '/largeMonsters'
      preLoaderRoute: typeof LargeMonstersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/largeMonsters/': {
      id: '/largeMonsters/'
      path: '/'
      fullPath: '/largeMonsters/'
      preLoaderRoute: typeof LargeMonstersIndexRouteImport
      parentRoute: typeof LargeMonstersRouteRoute
    }
    '/largeMonsters/$largeMonsterGameId': {
      id: '/largeMonsters/$largeMonsterGameId'
      path: '/$largeMonsterGameId'
      fullPath: '/largeMonsters/$largeMonsterGameId'
      preLoaderRoute: typeof LargeMonstersLargeMonsterGameIdRouteImport
      parentRoute: typeof LargeMonstersRouteRoute
    }
  }
}

interface LargeMonstersRouteRouteChildren {
  LargeMonstersLargeMonsterGameIdRoute: typeof LargeMonstersLargeMonsterGameIdRoute
  LargeMonstersIndexRoute: typeof LargeMonstersIndexRoute
}

const LargeMonstersRouteRouteChildren: LargeMonstersRouteRouteChildren = {
  LargeMonstersLargeMonsterGameIdRoute: LargeMonstersLargeMonsterGameIdRoute,
  LargeMonstersIndexRoute: LargeMonstersIndexRoute,
}

const LargeMonstersRouteRouteWithChildren =
  LargeMonstersRouteRoute._addFileChildren(LargeMonstersRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LargeMonstersRouteRoute: LargeMonstersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
